services:
  api:
    build: .
    container_name: fastapi_app
    env_file: .env
    #ports:
     # - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d appdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build: ../
    container_name: nextjs_app
    #ports:
    #  - "3000:3000"
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"    # Expone el puerto 80 (para redirigir a HTTPS)
      - "443:443"  # Expone el puerto 443 (para HTTPS)
    volumes:
      # Monta tu archivo de configuración
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # Monta tus certificados
      - ./nginx/ssl:/etc/nginx/ssl
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - api  # Se asegura de iniciar después de la API
    restart: unless-stopped
    
volumes:
  pgdata:
